### ISSUE TITLE
Cannot break in first statement

### ISSUE THREAD

**Issue by doublex** [addiks/gedit-dbgp-plugin#1]
This plugin is a missing-link! Thanks a lot.
I have some problems:

```
php.ini:
zend_extension=xdebug.so
xdebug.idekey=GEDIT

`php -i  | grep -i xdebug`
xdebug support => enabled
xdebug.remote_port => 9000 => 9000

profiles:
connect to DBGp not checked
URL to call: [empty]
Port: 9000
IDE-Key: GEDIT

"Start listening for debug-sessions"
Setting a break-point

`netstat -antp | grep gedit`:
0.0.0.0:9000            0.0.0.0:*               LISTEN      30498/gedit

> php -d xdebug.remote_autostart=1 test.php
```

Does not work. What is my problem?

**Comment by addiks** [comment]
I think you are missing the "xdebug.remote_enable=1" setting. Without that remote-debugging is disabled in xdebug. My working config (_/etc/php5/cli/conf.d/20-xdebug.ini_):

```
zend_extension=/usr/lib/php5/20121212/xdebug.so

[xdebug]

xdebug.remote_autostart=0
xdebug.remote_enable=1
xdebug.remote_log=/tmp/xdebug.log
xdebug.max_nesting_level=1000 ; needed for symfony (Maximum function nesting level of '100' reached, aborting!)
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_port=9000
xdebug.remote_host=127.0.0.1
```

**Comment by doublex** [comment]
Hi,
Strange, it works if I set a breakpoint in to line 3+, but not in line 2.
This was my PHP file:

```
<?php
echo "test\n";
echo "test\n";
echo "test\n";
echo "test\n";
echo "test\n";
```

Thanks a lot for this great missing link!

**Comment by addiks** [comment]
You are right, i can confirm that on my machine. But it does not depend on the line-number, but on the executed statement. It just seems to skip the first statement and just holds on the second. I can make it hold on the first line with this script:

```
<?php echo "123\n"; echo "123\n";
echo "123\n";
echo "123\n";
echo "123\n";
echo "123\n";
echo "123\n";
echo "123\n";
```

I will have a look at this issue when i have time again. There are also other issues which i want to solve before this (some hangs when using the step commands when the process is not currently breaking). Thanks for bringing this to my attention!

**Comment by doublex** [comment]
Danke!
Schöne Grüße aus Wien

**Comment by addiks** [comment]
This should be now fixed in the latest version. Can you confirm that?
