### ISSUE TITLE
Having trouble in gedit 3.14.0

### ISSUE THREAD

**Issue by progga** [addiks/gedit-dbgp-plugin#10]
Hi,
I am using this plugin with Gedit 3.14.0 in Debian 8.5.  Whenever I enable this plugin, I get the following error message:
`Traceback (most recent call last):
  File "/home/ju/.local/share/gedit/plugins/gedit-dbgp-plugin/AddiksDBGP/AddiksDBGPApp.py", line 65, in do_activate
    mainMenu.append_item(item)
AttributeError: 'NoneType' object has no attribute 'append_item'`

It appear to be a problem with the menu, so I copy-pasted some menu-related code from the [Crypto](http://pietrobattiston.it/gedit-crypto) plugin and it seem to be working okay.  Here is a diff of what I have got:

`diff --git a/AddiksDBGP/AddiksDBGPApp.py b/AddiksDBGP/AddiksDBGPApp.py
index 4ff11d6..8e8f099 100644
--- a/AddiksDBGP/AddiksDBGPApp.py
+++ b/AddiksDBGP/AddiksDBGPApp.py
@@ -58,11 +58,10 @@ class AddiksDBGPApp(GObject.Object, Gedit.AppActivatable):
         AddiksDBGPApp.__instance = self

```
     if "extend_menu" in dir(self): # build menu for gedit 3.12 (one menu per application)
```
-            self.submenu_ext = self.extend_menu("tools-section-1")
           submenu = Gio.Menu()
           item = Gio.MenuItem.new_submenu(_("Debugging"), submenu)
  -
-            mainMenu = self.app.get_menubar()
-            mainMenu.append_item(item)
- ```
         self.submenu_ext.append_menu_item(item)
  
       for actionName, title, shortcut, callbackName in ACTIONS:
           if callbackName != None:
  ```
  
  `
  I am not an expert on gedit plugins, so I am not presenting this diff for inclusion in the gedit-xdebug plugin, instead I am providing it just to explain the problem.  Hope it will help you under the issue.

Thanks,
Adnan

**Comment by addiks** [comment]
Looks like your patch was destroyed by markdown, can you please attach it as a seperate file? gedit-3.14 is indeed a version i have not tested yet. I am currently at work, so i cannot look at it for now. I will have a look at this when i am at home again.

**Comment by addiks** [comment]
The original code is supposed to add the "Debugging" menu as a new top-level menu while "your" patched version add's the menu as a submenu of the "Tools" menu. I don't know why the main-menu is not available in your version (resulting in the error), but whatever. I have pushed a new version that contains a fallback that add's the "Debugging" menu as a child of the tools-menu is the main-menu is not available. Can you please test that version and report back if that works for you or not?

**Comment by progga** [comment]
Thanks for looking into it so quickly.  The latest commit (bbad0d45) works if I use "self.submenuExt" instead of "submenuExt".  I have attached a patch this time :)
[submenu-diff-issue-10.txt](https://github.com/addiks/gedit-dbgp-plugin/files/469430/submenu-diff-issue-10.txt)

**Comment by addiks** [comment]
Are you sure about that? I see absolutely no reason why this variable needs be to a member of the plugin's app-object or why this should have any effect at all. Especially because "submenuExt" is a name i have defined myself, that should not be in use anywhere else.

**Comment by progga** [comment]
I know it sounds unreasonable, but it just does not work :(  I have tried it a few minutes ago with and without "self." being prepended to "submenuExt" and the menu item disappears without "self."

**Comment by addiks** [comment]
I have now pushed a new version that contains that "self.". It still does not make sense to me, but if it works for you i guess it's ok. Can you please test that version and report back?

**Comment by progga** [comment]
Just tried it and can confirm that it works. Thanks a ton :-)
